[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT"
homepage = "https://github.com/base/reth"
repository = "https://github.com/base/reth"

[workspace]
resolver = "2"
members = [
    "crates/flashblocks-rpc",
    "crates/node"
]

default-members = ["crates/node"]

[workspace.lints]

[workspace.dependencies]
# internal
base-reth-flashblocks-rpc = { path = "crates/flashblocks-rpc" }
base-reth-node = { path = "crates/node" }

# reth
reth = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-optimism-node = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-optimism-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-rpc-eth-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-optimism-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-rpc-types-compat = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-optimism-rpc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-optimism-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-optimism-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-exex = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }

# revm
revm = { version = "22.0.1", default-features = false }
revm-bytecode = { version = "3.0.0", default-features = false }

# alloy
alloy-primitives = { version = "1.0.0", default-features = false, features = ["map-foldhash"] }
alloy-eips = { version = "0.14.0", default-features = false }
alloy-rpc-types = { version = "0.14.0", default-features = false }
alloy-rpc-types-engine = { version = "0.14.0", default-features = false }
alloy-rpc-types-eth = { version = "0.14.0" }
alloy-consensus = { version = "0.14.0" }
alloy-trie = { version = "0.8.1", default-features = false }
alloy-provider = { version = "0.14.0" }
alloy-hardforks = "0.2.0"

# op-alloy
op-alloy-rpc-types = { version = "0.14.1", default-features = false }
op-alloy-rpc-types-engine = { version = "0.14.1", default-features = false }
op-alloy-rpc-jsonrpsee = { version = "0.14.1", default-features = false }
op-alloy-network = { version = "0.14.1", default-features = false }
op-alloy-consensus = { version = "0.14.1", default-features = false }

# rollup-boost
rollup-boost = { git = "http://github.com/flashbots/rollup-boost", rev = "60885346d4cf7f241de82790478195747433d472" }
rustls = "0.23.23"

# tokio
tokio = { version = "1.44.2", features = ["full"] }
tokio-stream = "0.1.11"
tokio-tungstenite = { version = "0.26.2", features = ["native-tls"] }

# async
futures = "0.3"
futures-util = "0.3"
reqwest = { version = "0.11", features = ["json", "stream"] }

# rpc
jsonrpsee = { version = "0.24.8" }

# misc
clap = { version = "4.4.3" }
tracing = { version = "0.1.41" }
serde = "1"
serde_json = "1.0"
url = "2.5"
metrics = "0.24.1"
metrics-derive = "0.1"
itertools = "0.12"
eyre = { version = "0.6.12" }
uuid = { version = "1.6.1", features = ["serde", "v5", "v4"] }
time = { version = "0.3.36", features = ["macros", "formatting", "parsing"] }
chrono = "0.4"